cmake_minimum_required(VERSION 3.22)
project(vulkano LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_library(vulkano_core STATIC graphs.cpp graph_shaders.cpp graph_queues.cpp tensor_shaders.cpp tensors.cpp tiles.cpp generated.cpp engine.cpp matrices.cpp subpasses.cpp resources.cpp extensions.cpp ray.cpp ray_archive.cpp synchronization.cpp heaps.cpp sparse.cpp interop.cpp allocator.cpp third_party/spirv-reflect/spirv_reflect.c)
set_target_properties(vulkano_core PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(vulkano_core PUBLIC .)
target_include_directories(vulkano_core SYSTEM BEFORE PUBLIC third_party/vulkan-headers/include)
target_include_directories(vulkano_core SYSTEM PRIVATE third_party)
target_compile_definitions(vulkano_core PUBLIC VMA_VULKAN_VERSION=1003000 VMA_STATIC_VULKAN_FUNCTIONS=0 VMA_DYNAMIC_VULKAN_FUNCTIONS=1)
target_compile_options(vulkano_core PRIVATE -Wall -Wextra -Werror -Wno-missing-field-initializers)
set_source_files_properties(allocator.cpp PROPERTIES COMPILE_OPTIONS "-w")
set_source_files_properties(third_party/spirv-reflect/spirv_reflect.c PROPERTIES COMPILE_OPTIONS "-w")

if(ANDROID)
    target_compile_definitions(vulkano_core PUBLIC VK_USE_PLATFORM_ANDROID_KHR)
    target_link_libraries(vulkano_core PUBLIC vulkan android dl)
else()
    find_package(Vulkan REQUIRED)
    target_link_libraries(vulkano_core PUBLIC Vulkan::Vulkan)
    find_package(JNI REQUIRED COMPONENTS JVM)
endif()

add_library(vulkano SHARED jni.cpp)
target_link_libraries(vulkano PRIVATE vulkano_core)
target_include_directories(vulkano SYSTEM PRIVATE third_party)
target_compile_options(vulkano PRIVATE -Wall -Wextra -Werror -Wno-missing-field-initializers)
if(ANDROID)
    target_link_options(vulkano PRIVATE "-Wl,-z,max-page-size=16384" "-Wl,-z,common-page-size=16384")
else()
    target_include_directories(vulkano PRIVATE ${JNI_INCLUDE_DIRS})
    enable_testing()
    add_executable(vulkano_tests ../../../../tests/native/engine_test.cpp)
    target_include_directories(vulkano_tests SYSTEM PRIVATE third_party)
    target_link_libraries(vulkano_tests PRIVATE vulkano_core)
    target_compile_definitions(vulkano_tests PRIVATE VULKANO_TEST_ASSETS="${CMAKE_CURRENT_SOURCE_DIR}/../../../../tests/shaders")
    add_test(NAME vulkano_tests COMMAND vulkano_tests)
endif()
