#version 450
layout(local_size_x=1) in;
layout(set=0,binding=0,std430) buffer Arguments { uint args[]; };
layout(set=0,binding=1,std430) buffer Counts { uint counts[]; };
layout(push_constant) uniform Control { uint mode; uint count; uvec2 vertices; uvec2 indices; } control;
void main() {
    uint stride = control.mode == 2 ? 15 : control.mode == 1 ? 6 : 5;
    for (uint i = 0; i < 2; ++i) {
        uint at = i * stride;
        args[at++] = i;
        args[at++] = control.mode == 0 ? 7+i : floatBitsToUint(float(i+1) * 0.25);
        if (control.mode == 2) {
            args[at++] = control.vertices.x; args[at++] = control.vertices.y;
            args[at++] = 24; args[at++] = 8;
            args[at++] = control.indices.x; args[at++] = control.indices.y;
            args[at++] = 6; args[at++] = 0;
        }
        args[at++] = control.mode == 0 || control.mode == 3 ? 1 : 3;
        args[at++] = 1;
        args[at++] = control.mode == 0 || control.mode == 3 ? 1 : 0;
        if (control.mode == 1 || control.mode == 2) args[at++] = 0;
        if (control.mode == 2) args[at++] = 0;
    }
    counts[1] = control.count;
}
