#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_NV_ray_tracing_motion_blur : require
layout(binding = 0) uniform accelerationStructureEXT scene;
layout(binding = 1) buffer Result { uint hits[]; } result;
layout(location = 0) rayPayloadEXT uint hit;
void main() {
    uint index = gl_LaunchIDEXT.x;
    hit = 0;
    traceRayMotionNV(scene, gl_RayFlagsOpaqueEXT, 255, 0, 0, 0,
        vec3(0, 0, -1), 0.001, vec3(0, 0, 1), 100.0, float(index) * 0.5, 0);
    result.hits[index] = hit;
}
